version: '3'

services: 
  cas2: 
    container_name: cassan2
    image: cassandra:latest
    volumes:
      - ./../data/cassandra/node1:/var/lib/cassandra
    ports:
      - 9042:9042
    environment:
      - CASSANDRA_START_RPC=true
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
      - CASSANDRA_DC=datacenter1
    networks:
      - assignment
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: deployments/app/Dockerfile
    volumes:
      - ./../data/server:/server
    tty: true
    ports:
      - 5000:5000
    networks:
      - assignment
  mqtt:
    container_name: databroker
    image: eclipse-mosquitto:latest
    restart: always
    volumes:
      - ./../data/mqtt:/var/log/
    ports:
      - 1883:1883
      - 9001:9001
    networks:
      - assignment

  zookeeper:
    image: zookeeper
    container_name: zookeeper
    restart: always
    networks:
      - assignment
    ports:
      - 2181:2181
  nimbus:
    image: storm
    container_name: nimbus
    command: storm nimbus
    depends_on:
      - zookeeper
      - mqtt
    # links:
    #   - zookeeper
    #   - mqtt
    networks:
      - assignment
    restart: always
    ports:
      - 6627:6627
      - 8000:8000
  supervisor:
    image: storm
    container_name: supervisor
    command: storm supervisor
    depends_on:
      - nimbus
      - zookeeper
      - mqtt
    # links:
    #   - nimbus
    #   - zookeeper
    #   - mqtt
    networks:
      - assignment
    restart: always
  storm-ui: 
    image: storm
    container_name: storm-ui
    command: storm ui
    depends_on: 
        - nimbus
        - zookeeper
    # links: 
    #     - nimbus
    #     - zookeeper
    networks:
      - assignment
    restart: always
    ports:
        - "8080:8080"

networks:
  assignment: {}

    
